on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_IMAGE: ranmarkovich/devops-backend-app

jobs:
  extract_metadata:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    steps:
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=commit-

  build_test_and_push_backend:
    needs: extract_metadata
    uses: RanM-DevOpsLabs/CI-CD-Labs/.github/workflows/backend-ci-cd.yml@main
    with:
      labels: ${{ needs.extract_metadata.outputs.labels }}
      tags: ${{ needs.extract_metadata.outputs.tags }}